name: Build and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create config file
        run: |
          echo "const CONFIG = {" > config.js
          echo "  RAPIDAPI_KEY: '${{ secrets.RAPIDAPI_KEY }}'" >> config.js
          echo "};" >> config.js

      - name: List files
        run: |
          echo "Current directory structure:"
          ls -R
          echo "Contents of config.js:"
          cat config.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
