name: Build and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create config file
        run: |
          cat > config.js << 'EOL'
          const CONFIG = {
            RAPIDAPI_KEY: '${{ secrets.RAPIDAPI_KEY }}'
          };
          EOL

      - name: Verify files
        run: |
          echo "=== Directory contents ==="
          ls -la
          echo "=== Config.js contents ==="
          cat config.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true
